env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/zr-stackexchange/main.go
    binary: zr-stackexchange
    id: zr-stackexchange
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
  - main: ./cmd/zr-stdin/main.go
    binary: zr-stdin
    id: zr-stdin
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
  - main: ./cmd/zr/main.go
    binary: zr
    id: zr
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
  - main: ./cmd/zr-reindex/main.go
    binary: zr-reindex
    id: zr-reindex
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64

archives:
  - name_template: '{{ .ProjectName }}_{{.Tag}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: macOS
      386: i386
      amd64: x86_64
