on:
  push:
    tags:
    - 'v*'
jobs:
  goreleaser:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      -
        name: Run GoReleaser Linux
        if: matrix.os == 'ubuntu-latest'
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist -f .goreleaser.linux.yml
          key: ${{ secrets.YOUR_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Run GoReleaser Darwin
        if: matrix.os == 'macos-latest'
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist -f .goreleaser.darwin.yml
          key: ${{ secrets.YOUR_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Run GoReleaser Windows
        if: matrix.os == 'windows-latest'
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist -f .goreleaser.windows.yml
          key: ${{ secrets.YOUR_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
